apiVersion : apps/v1
kind: Deployment
metadata:
  name: gjuly22aks2 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gjuly22aks2
  template:
    metadata:
      labels:
        app: gjuly22aks2 
    spec:
      containers:
        - name: gjuly22aks2 
          image: azurecontregjuly21.azurecr.io/sunday1
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: gjuly22aks2
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: gjuly22aks2